</h2>Part A: Probabilistic Gaussian Generative Classifier

part A

In [91]:
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
import sklearn.preprocessing
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


digits = sklearn.datasets.load_digits()
X, y = digits.data, digits.target

X_train, X_remaining, y_train, y_remaining = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y)

X_val, X_test, y_val, y_test = train_test_split(
    X_remaining, y_remaining, test_size=0.50, random_state=42, stratify=y_remaining)

scaler = sklearn.preprocessing.StandardScaler()

# fit: to compute mean and std dev 
# transform: perform scaling using mean and std dev calculated by fit 
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_val_scaled = scaler.transform(X_val)  



</h4>part A2

In [92]:
pi_k = {}
mean = {}
cov = {}
reg_cov = {}
D = X_train_scaled.shape[1]
sum_samples = np.zeros((D, D))
for k in range(10):
    Xk = X_train_scaled[y_train == k]
    pi_k[k] = len(Xk)/len(X_train_scaled) # (prior) probability of each class k
    mean[k] = np.mean(Xk, axis=0) # axis=0 mean of each column 

# shared covariance matrix

diff = X_train_scaled - np.array([mean[y] for y in y_train]) # difference between feature of samples and mean (#samples,D)
shared_cov = (diff.T @ diff) / len(X_train_scaled)




prediction function

In [93]:
def predicted_number(x,pi_k,mean,inv_cov,logdet):
    N = x.shape[0]
    prob = np.zeros((N,10))
    for i in range(10):
        diff = x - mean[i]
        prob[:,i] = np.log(pi_k[i]) - 0.5*logdet - 0.5 * np.sum(diff @ inv_cov * diff, axis=1) 
    
    return np.argmax(prob, axis=1) 



part A3

In [94]:
lambda_values = [1e-4, 1e-3, 1e-2, 1e-1]
val_accuracies = []
for l in lambda_values:
    reg_cov = shared_cov + l * np.eye(D)
    inv_cov = np.linalg.inv(reg_cov)
    logdet = np.linalg.slogdet(reg_cov)[1] # log of determinant

    y_val_pred = predicted_number(X_val_scaled,pi_k,mean,inv_cov,logdet)
    val_accuracy = np.mean(y_val == y_val_pred)
    val_accuracies.append(val_accuracy)
    print(f"λ={l}, validation accuracy=  {val_accuracy:.5}")

idx = np.argmax(val_accuracies)
best_lambda = lambda_values[idx]
print("\nBest λ =", best_lambda, "with validation accuracy =", val_accuracies[idx])

X_combined = np.vstack([X_train_scaled, X_val_scaled])
y_combined = np.hstack([y_train, y_val])

y_test_pred = predicted_number(X_test,pi_k,mean,inv_cov,logdet)
acc  = accuracy_score(y_test, y_test_pred)
print("\nTest Accuracy before combination:", acc)

#retrain 

pi_k_comp = {}
mean_comp = {}
cov_comp = {}
reg_cov_comp = {}
D = X_combined.shape[1]
sum_samples = np.zeros((D, D))
for k in range(10):
    Xk = X_combined[y_combined == k]
    pi_k_comp[k] = len(Xk)/len(X_combined) # (prior) probability of each class k
    mean_comp[k] = np.mean(Xk, axis=0) # axis=0 mean of each column 



diff = X_combined - np.array([mean_comp[y] for y in y_combined]) # difference between feature of samples and mean (#samples,D)
shared_cov = (diff.T @ diff) / len(X_combined)
reg_cov_comp = shared_cov + best_lambda * np.eye(D)
inv_cov_comp = np.linalg.inv(reg_cov_comp)
logdet_comp = np.linalg.slogdet(reg_cov_comp)[1] # log of determinant



λ=0.0001, validation accuracy=  0.94444
λ=0.001, validation accuracy=  0.94444
λ=0.01, validation accuracy=  0.94444
λ=0.1, validation accuracy=  0.94444

Best λ = 0.0001 with validation accuracy = 0.9444444444444444

Test Accuracy before combination: 0.9296296296296296


Evaluate on testset

In [95]:
y_test_pred = predicted_number(X_test_scaled,pi_k_comp,mean_comp,inv_cov_comp,logdet_comp)

acc  = accuracy_score(y_test, y_test_pred)
prec = precision_score(y_test, y_test_pred, average="macro")
rec  = recall_score(y_test, y_test_pred, average="macro")
f1   = f1_score(y_test, y_test_pred, average="macro")
cm   = confusion_matrix(y_test, y_test_pred)

print("=== FINAL TEST RESULTS ===")
print("Accuracy :", acc)
print("Precision:", prec)
print("Recall   :", rec)
print("F1 Score :", f1)
print("\nConfusion Matrix:")
print(cm)

=== FINAL TEST RESULTS ===
Accuracy : 0.9629629629629629
Precision: 0.9631904761904762
Recall   : 0.9626577126577127
F1 Score : 0.9624803472389681

Confusion Matrix:
[[27  0  0  0  0  0  0  0  0  0]
 [ 0 26  0  0  0  0  0  0  1  1]
 [ 0  0 26  0  0  0  0  0  0  0]
 [ 0  0  0 28  0  0  0  0  0  0]
 [ 0  0  0  0 27  0  0  0  0  0]
 [ 0  0  0  0  0 27  0  0  0  0]
 [ 0  0  0  0  0  0 27  0  0  0]
 [ 0  0  0  0  0  0  0 27  0  0]
 [ 0  3  0  0  0  0  0  0 22  1]
 [ 0  1  0  0  0  1  0  1  1 23]]


Part B: Naïve Bayes 

Part C: Decision Trees

Part D: Random Forest